### ISSUE TITLE
While following the tutorial I get "can't find crate for `test`" while compiling for unit test execution

### ISSUE THREAD

**Issue by 2ndTaleStudio** [rust-embedded/rust-raspberrypi-OS-tutorials#78]
Hi there,

I'm using a custom build target for my Raspberry Pi bare metal kernel. After setting everything up and compiling the binary kernel for unit testing I get the compiler error "can't find crate for `test`".

Any clue what might be the root cause for this?

I'm not using cargo xbuild, but the new cross compile configuration in /.cargo/config like so:
```toml
[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
```

Any help would be much appreciated.

Thanks in advance.
